import React, { useState } from "react";
import InputForm from "../components/InputForm";
import OutputSection from "../components/OutputSection";

function Home() {
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  return (
    <div className="min-h-screen bg-gray-50 px-6 py-10 md:px-24">
      <h1 className="text-3xl md:text-4xl font-bold text-center mb-10 text-indigo-600">
        🧠 Text Summarization & MCQ Generator
      </h1>
      <InputForm setResult={setResult} setLoading={setLoading} />
      <OutputSection result={result} loading={loading} />
    </div>
  );
}

export default Home;


// import React, { useState } from "react";
// import Header from "../components/Header";
// import TextInput from "../components/TextInput";
// import ResultsDisplay from "../components/ResultsDisplay";

// const Home = () => {
//   const [results, setResults] = useState({
//     summary: "",
//     keywords: [],
//     mcqs: [],
//   });
//   const [isLoading, setIsLoading] = useState(false);

//   const handleSubmit = async (text) => {
//     // setIsLoading(true);
//     try {
//       // This is where you'll call your backend API
//       // For now, we'll simulate a response
//       // const response = await axios.post('YOUR_BACKEND_API_ENDPOINT', { text });
//       // setResults(response.data);

//       // Simulated response (remove this in production)
//       setTimeout(() => {
//         setResults({
//           summary: "This is a simulated summary of the input text. In a real implementation, this would be generated by your NLP model.",
//           keywords: ["simulated", "summary", "text", "implementation", "model"],
//           mcqs: [
//             {
//               question: "What is this example demonstrating?",
//               options: [
//                 "A real NLP implementation",
//                 "A simulated response",
//                 "A database query",
//                 "A frontend bug",
//               ],
//               answer: "b",
//             },
//             {
//               question: "Which technology is used for styling in this project?",
//               options: ["Bootstrap", "Tailwind CSS", "Material UI", "Sass"],
//               answer: "b",
//             },
//           ],
//         });
//         setIsLoading(false);
//       }, 2000);
//     } catch (error) {
//       console.error("Error processing text:", error);
//       setIsLoading(false);
//     }
//   };

//   return (
//     <div className="min-h-screen bg-gray-50">
//       <Header />
//       <main className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
//         <div className="px-4 py-6 sm:px-0">
//           <TextInput onSubmit={handleSubmit} isLoading={isLoading} />
//           <ResultsDisplay
//             summary={results.summary}
//             keywords={results.keywords}
//             mcqs={results.mcqs}
//             isLoading={isLoading}
//           />
//         </div>
//       </main>
//     </div>
//   );
// };

// export default Home;